
spring:
  main:
    banner-mode: off
    web-application-type: none
logging:
  level:
    root: warn
    '[org.springframework]': warn
    '[com.github.dbranco.jaguar]': warn
    '[com.github.dbranco.jaguar.*]': info
jaguar:
  list:
    url: "https://raw.githubusercontent.com/dbranco/jaguar/main/src/main/resources/list.json"
